import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google"
import { Toaster } from "@/components/ui/toaster";


const dm_sans = DM_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white ${dm_sans.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
