export enum UserStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  SUSPENDED = 'SUSPENDED',
}

export enum UserRoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum PermissionType {
  PAGE_ACCESS = 'PAGE_ACCESS',
  FEATURE_ACCESS = 'FEATURE_ACCESS',
  DATA_ACCESS = 'DATA_ACCESS',
}
