export enum UserStatusEnum {
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BANNED = 'BANNED',
  DELETED = 'DELETED',
}

export enum PermissionType {
  PAGE_ACCESS = 'PAGE_ACCESS',
  FEATURE_ACCESS = 'FEATURE_ACCESS',
  DATA_ACCESS = 'DATA_ACCESS',
}
